### PR TITLE
Documentation/cli updates

### PR DESCRIPTION
**Pull request by pomeroy3**
Adding in documentation updates to reduce issues users have been having when trying to build the module

### CODE REVIEW

**Comment by robotastic** [comment]
Does it make  sense to move the detailed writeups of the Examples from the main Readme to the Readme in the examples dir? In the main readme, we could just link to the examples and have a short description of what each block does.

**Comment by 777arc** [comment]
> For the Deploy Azure and Cloudshell links, it might be nice to automatically open it in a new tab. Not sure what other tutorials are doing though. If you just use HTML instead of the Markdown link, the following should work: `<a href="http://example.com/" target="_blank">example</a>`

Done, great idea

**Review by 777arc — APPROVED** [review]
Definitely WAY better than what's currently on main, tons of overhauls, I think a couple spots will be further attention (e.g. blob quickstart) but I hate to see that block this one, and it would be nice to work on those in individual branches/PRs instead of this massive one

**Comment by 777arc** [comment]
Leaving branch open for a little bit, for the sake of the "deploy to azure" urls on people's local copies

**Pull request merged**
